[package]
name = "libp2p-autonat"
version = "0.20.0"
authors = ["David Craven <david@craven.ch>", "Elena Frank <elena.frank@protonmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/libp2p/rust-libp2p"
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]

[build-dependencies]
prost-build = "0.6"

[dependencies]
async-trait = "0.1"
futures = "0.3"
futures-timer = "3.0.2"
libp2p-core = { version = "0.30.1", path = "../../core" }
libp2p-swarm = { version = "0.32.0", path = "../../swarm" }
libp2p-request-response = { version = "0.14.0", path = "../request-response" }
prost = "0.8"
