[package]
name = "libp2p-autonat"
edition = "2021"
rust-version = "1.56.1"
version = "0.20.0"
authors = ["David Craven <david@craven.ch>", "Elena Frank <elena.frank@protonmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/libp2p/rust-libp2p"
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]

[build-dependencies]
prost-build = "0.6"

[dependencies]
async-trait = "0.1"
futures = "0.3"
futures-timer = "3.0.2"
libp2p-core = { version = "0.30.1", path = "../../core", default-features = false }
libp2p-swarm = { version = "0.32.0", path = "../../swarm" }
libp2p-request-response = { version = "0.14.0", path = "../request-response" }
prost = "0.8"

[dev-dependencies]
async-process = "1.3"
async-std = { version = "1.10", features = ["attributes"] }
env_logger = "0.9"
libp2p = { path = "../../", default-features = false, features = ["dns-async-std", "mplex", "noise", "tcp-async-io", "websocket", "yamux"]}
netsim-embed = "0.5.2"
